#!/usr/bin/env bash
set -euo pipefail

# LISA build script
# Automated local flow for lint, simulation, and synthesis.

PROJECT="lisa"
TOP_MODULE="lisa_bytecode_core"
TESTBENCH_MODULE="tb_lisa_bytecode_core"

# Directories
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RTL_DIR="$ROOT_DIR/rtl"
TB_DIR="$ROOT_DIR/tb"
SYNTH_DIR="$ROOT_DIR/synth"
BUILD_DIR="$ROOT_DIR/build"
SIM_DIR="$BUILD_DIR/sim"
REPORTS_DIR="$SYNTH_DIR/reports"

# Tools
VERILATOR="verilator"
IVERILOG="iverilog"
VVP="vvp"
YOSYS="yosys"

# Flags
VERILATOR_FLAGS="--lint-only -Wall -Wno-fatal"
IVERILOG_FLAGS="-g2005-sv -Wall"

# Outputs
TB_FILE="${TB_FILE:-$TB_DIR/tb_lisa_bytecode_core.v}"
SIM_OUTPUT="$SIM_DIR/${TESTBENCH_MODULE}.vvp"
WAVE_OUTPUT="$SIM_DIR/waveforms/${TESTBENCH_MODULE}.vcd"
SYNTH_SCRIPT="$SYNTH_DIR/synth.ys"
SYNTH_NETLIST="$REPORTS_DIR/lisa_bytecode_core_synth.v"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

cd "$ROOT_DIR"

usage() {
  echo -e "${BLUE}LISA Build System${NC}"
  echo ""
  echo "Usage: $0 [target]"
  echo ""
  echo "Available targets:"
  echo "  all      - Run complete local flow (lint + check + sim + synth)"
  echo "  lint     - Run Verilator linting"
  echo "  check    - Run structural checks with Yosys"
  echo "  build    - Compile simulation binary with Icarus Verilog"
  echo "  sim      - Run simulation with Icarus Verilog"
  echo "  synth    - Run synthesis with Yosys (synth/synth.ys)"
  echo "  test     - Quick test (lint + sim)"
  echo "  ci       - CI entrypoint (lint + check + sim + synth)"
  echo "  clean    - Remove generated artifacts"
  echo "  help     - Show this help message"
  echo ""
  echo "Environment overrides:"
  echo "  TB_FILE  - Testbench file (default: tb/tb_lisa_bytecode_core.v)"
  echo ""
}

need_tool() {
  local tool="$1"
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo -e "${RED}error:${NC} required tool '$tool' was not found in PATH" >&2
    exit 1
  fi
}

collect_rtl_sources() {
  shopt -s nullglob
  RTL_SOURCES=("$RTL_DIR"/*.v)
  shopt -u nullglob

  if [ ${#RTL_SOURCES[@]} -eq 0 ]; then
    echo -e "${RED}error:${NC} no RTL sources found in $RTL_DIR" >&2
    exit 1
  fi
}

lint() {
  echo -e "${BLUE}Running Verilator lint...${NC}"
  need_tool "$VERILATOR"
  collect_rtl_sources

  mkdir -p "$REPORTS_DIR"
  : > "$REPORTS_DIR/lint.log"

  "$VERILATOR" $VERILATOR_FLAGS -I"$RTL_DIR" "${RTL_SOURCES[@]}" \
    2>&1 | tee -a "$REPORTS_DIR/lint.log"

  echo -e "${GREEN}✓ Linting completed${NC}"
}

check() {
  echo -e "${BLUE}Running Yosys structural checks...${NC}"
  need_tool "$YOSYS"

  mkdir -p "$REPORTS_DIR"
  "$YOSYS" -p "read_verilog rtl/*.v; hierarchy -check -top $TOP_MODULE; proc; check" \
    2>&1 | tee "$REPORTS_DIR/check.log"

  echo -e "${GREEN}✓ Structural checks completed${NC}"
}

build() {
  echo -e "${BLUE}Compiling testbench...${NC}"
  need_tool "$IVERILOG"
  collect_rtl_sources

  if [ ! -f "$TB_FILE" ]; then
    echo -e "${RED}error:${NC} testbench file not found: $TB_FILE" >&2
    exit 1
  fi

  mkdir -p "$SIM_DIR"
  "$IVERILOG" $IVERILOG_FLAGS -o "$SIM_OUTPUT" "$TB_FILE" "${RTL_SOURCES[@]}"

  echo -e "${GREEN}✓ Build completed${NC}"
  echo -e "${YELLOW}Simulation binary:${NC} $SIM_OUTPUT"
}

sim() {
  echo -e "${BLUE}Running simulation...${NC}"
  need_tool "$VVP"

  build
  "$VVP" "$SIM_OUTPUT"

  echo -e "${GREEN}✓ Simulation completed${NC}"
  echo -e "${YELLOW}Waveform path (if generated by testbench):${NC} $WAVE_OUTPUT"
}

synth() {
  echo -e "${BLUE}Running synthesis...${NC}"
  need_tool "$YOSYS"

  if [ ! -f "$SYNTH_SCRIPT" ]; then
    echo -e "${RED}error:${NC} synthesis script not found: $SYNTH_SCRIPT" >&2
    exit 1
  fi

  mkdir -p "$REPORTS_DIR"
  "$YOSYS" -s "$SYNTH_SCRIPT" 2>&1 | tee "$REPORTS_DIR/synthesis.log"

  echo -e "${GREEN}✓ Synthesis completed${NC}"
  echo -e "${YELLOW}Synthesized netlist:${NC} $SYNTH_NETLIST"
  echo -e "${YELLOW}Synthesis log:${NC} $REPORTS_DIR/synthesis.log"
}

clean() {
  echo -e "${BLUE}Cleaning generated files...${NC}"
  rm -rf "$BUILD_DIR"
  rm -f "$REPORTS_DIR"/*.log
  rm -f "$SYNTH_NETLIST"
  echo -e "${GREEN}✓ Clean completed${NC}"
}

test() {
  lint
  sim
  echo -e "${GREEN}✓ Quick test completed${NC}"
}

all() {
  lint
  check
  sim
  synth
  echo -e "${GREEN}✓ Complete flow finished successfully${NC}"
}

ci() {
  lint
  check
  sim
  synth
  echo -e "${GREEN}✓ CI flow finished successfully${NC}"
}

case "${1:-help}" in
  all)
    all
    ;;
  lint)
    lint
    ;;
  check)
    check
    ;;
  build)
    build
    ;;
  sim)
    sim
    ;;
  synth)
    synth
    ;;
  test)
    test
    ;;
  ci)
    ci
    ;;
  clean)
    clean
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    echo -e "${RED}error:${NC} unknown target '$1'" >&2
    usage
    exit 2
    ;;
esac
